name: e2e-poc-build

on:
  push:
    branches: binary-e2e

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: start distribution
        run: |
          docker stop --name oras-e2e || true
          docker run -dp 5000:5000 --name oras-e2e ghcr.io/oras-project/registry:v0.0.3-alpha
      - name: Run Tests
        run: make test
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
      - name: stop distribution
        run: |
          docker stop --name oras-e2e || true
